version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432' #inspect
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: nodebackend_dev
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: yarn dev:docker
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/nodebackend_dev
      PORT: 8000
# "postgres://YourUserName:YourPassword@YourHostname:5432/YourDatabaseName";
